let Birds = []
let Bonuscards = []
class Bird {
  constructor(name, sci_name, cost, habitats, points, nest_type, max_eggs, wingspan, bird_power){
    this.name = name
    this.sci_name = sci_name
    this.cost = cost
    this.habitats = habitats
    this.points = points
    this.nest_type = nest_type
    this.max_eggs = max_eggs
    this.wingspan = wingspan 
    this.bird_power = bird_power
  }
}
class BonusCard {
  constructor(name, description, pointsdescription, percentage) {
    this.name = name
    this.description = description
    this.pointsdescription = pointsdescription
    this.percentage = percentage
  }
}
Birds.push( new Bird('savannah sparrow', 'passerculus sandwichensis', 'invertebrate or seed', 'grassland', 2, 'ground', 3, 18, 'when played: play and additional bird in your grassland. pay its normal cost'))
Birds.push( new Bird('american goldfinch', 'spinus tristis', 'seed and seed', 'grassland', 3, 'bowl', 3, 23, 'when played: gain 3 seed from the supply'))
Birds.push( new Bird('ring-billed gull', 'larus delawarensis', 'wild and wild', 'wetland', 4, 'ground', 2, 122, 'when activated: tuck 1 bird from your hand behind this bird. if you do, draw 1 bird'))
Birds.push( new Bird('red-cockaded woodpecker', 'picaides borealis', 'invertebrate and fruit', 'forest', 4, 'cavity', 2, 36, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird("clark's nutcracker", 'nucifraga columbiana', 'seed and seed and wild', 'forest', 5, 'platform', 2, 61, 'when activated: gain 1 seed from the birdfeeder, if available. you may cache it on this bird'))
Birds.push( new Bird('american kestrel', 'falco sparverius', 'invertebrate and rodent', 'grassland', 5, 'cavity', 3, 56, 'when activated: roll all dice not in birdfeeder. if any are rodent, cache 1 rodent from the supply on this bird'))
Birds.push( new Bird('tufted titmouse', 'baeolophus bicolor', 'invertebrate or seed or fruit', 'forest', 2, 'cavity', 3, 25, 'when played: play and additional bird in your forest. pay its normal cost'))
Birds.push( new Bird('black-bellied whistling-duck', 'dendrocygna autumnalis', 'seed and seed', 'wetland', 2, 'cavity', 5, 76, 'when activated: discard 1 seed to tuck 2 birds from the deck behind this bird'))
Birds.push( new Bird('chipping sparrow', 'spizella passerina', 'invertebrate or seed', 'grassland and forest', 1, 'bowl', 3, 23, 'when activated: lay 1 egg on any bird'))
Birds.push( new Bird('greater roadrunner', 'geocaccyx californianus', 'invertebrate and rodent and wild', 'grassland', 7, 'platform', 2, 56, 'when activated: look at a bird from the deck. if less then 50cm, tuck it behind this bird. if not, discard it'))
Birds.push( new Bird('pileated woodpecker', 'dryocopus pileatus', 'invertebrate and fruit', 'forest', 4, 'cavity', 2, 74, 'when activated: all players lay 1 egg on any 1 cavity bird. you may lay 1 egg on 1 additional cavity bird'))
Birds.push( new Bird('blue-gray gnatcatcher', 'polioptila caerulea', 'invertebrate', 'forest', 1, 'bowl', 3, 15, 'when activated: gain 1 invertebrate from the supply'))
Birds.push( new Bird('brown pelican', 'pelecanus accidentalis', 'fish and fish', 'wetland', 4, 'platform', 2, 201, 'when played: gain 3 fish from the supply'))
Birds.push( new Bird('blue grosbeak', 'passerina caerulea', 'invertebrate and seed and seed', 'wetland and grassland and forest', 4, 'bowl', 3, 28, 'when activated: if this bird is to the right of all other birds in its habitat, move it to another habitat'))
Birds.push( new Bird('western tanager', 'piranga ludoviciana', 'invertebrate and invertebrate and fruit', 'forest', 6, 'bowl', 2, 30, 'when activated: gain 1 invertebrate or fruit from the birdfeeder, if available'))
Birds.push( new Bird('american avocet', 'recurvirostra americana', 'invertebrate and invertebrate and seed', 'wetland', 6, 'ground', 2, 79, 'once between turns: when another player takes the "lay eggs" action, lay 1 egg on another bird with a ground nest'))
Birds.push( new Bird('american bittern', 'botaurus lentiginosus', 'invertebrate and fish and rodent', 'wetland', 7, 'platform', 2, 107, 'when activated: player(s) with the fewest birds in their wetland draw 1 bird'))
Birds.push( new Bird('california condor', 'gymnogyps californianus', 'none', 'wetland and grassland and forest', 1, 'ground', 1, 277, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('brant', 'branta bernicla', 'seed and wild', 'wetland', 3, 'ground', 2, 114, 'when played: draw the 3 face-up birds in the bird tray'))
Birds.push( new Bird('white-faced ibis', 'plegadis chihi', 'invertebrate and invertebrate and fish', 'wetland', 8, 'platform', 2, 91, 'when activated: roll all dice not in birdfeeder. if any are fish, cache 1 fish from the supply on this bird'))
Birds.push( new Bird('ruby-crowned kinglet', 'regulus calendula', 'invertebrate or seed or fruit', 'forest', 2, 'bowl', 3, 20, 'when played: play and additional bird in your forest. pay its normal cost'))
Birds.push( new Bird("say's phoebe", 'sayornis saya', 'invertebrate and invertebrate and invertebrate', 'grassland', 5, 'bowl', 3, 33, 'when played: lay 1 egg on each of your birds with a bowl nest'))
Birds.push( new Bird('atlantic puffin', 'fratercula arctica', 'fish and fish and fish', 'wetland', 8, 'star', 1, 53, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird("lincoln's sparrow", 'melaspiza lincolnii', 'invertebrate and fish', 'wetland and grassland and forest', 3, 'ground', 2, 20, 'when activated: if this bird is to the right of all other birds in its habitat, move it to another habitat'))
Birds.push( new Bird('gray catbird', 'dumetella carolinensis', 'invertebrate and fruit and fruit', 'wetland and grassland and forest', 5, 'bowl', 3, 28, 'when activated: repeat a brown power on another bird in this habitat'))
Birds.push( new Bird('black-necked stilt', 'himantopus mexicanus', 'invertebrate and invertebrate', 'wetland', 4, 'ground', 2, 74, 'when played: draw 2 birds'))
Birds.push( new Bird('burrowing owl', 'athene cunicularia', 'invertebrate and rodent', 'grassland', 5, 'star', 4, 53, 'when activated: roll all dice not in birdfeeder. if any are rodent, cache 1 rodent from the supply on this bird'))
Birds.push( new Bird('northern bobwhite', 'calinus virginianus', 'seed and seed and seed', 'grassland', 5, 'ground', 6, 33, 'when activated: lay 1 egg on this bird'))
Birds.push( new Bird('black skimmer', 'rynchops niger', 'fish and fish', 'wetland', 6, 'ground', 2, 112, 'when activated: roll all dice not in birdfeeder. if any are fish, cache 1 fish from the supply on this bird'))
Birds.push( new Bird('trumpeter swan', 'cygnus buccinator', 'seed and seed and wild', 'wetland', 9, 'ground', 2, 203, 'none'))
Birds.push( new Bird('whooping crane', 'grus americana', 'wild and wild and wild', 'wetland', 6, 'ground', 1, 221, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('black-chinned hummingbird', 'archilochus alexandri', 'wild', 'wetland and grassland and forest', 4, 'bowl', 2, 8, 'when activated: all players gain 1 fruit from the supply'))
Birds.push( new Bird('barn owl', 'tyto alba', 'rodent and rodent', 'wetland and grassland and forest', 5, 'cavity', 4, 107, 'when activated: roll all dice not in birdfeeder. if any are rodent, cache 1 rodent from the supply on this bird'))
Birds.push( new Bird('roseate spoonbill', 'platalea ajaja', 'invertebrate and seed and fish', 'wetland', 6, 'platform', 2, 127, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('mountain bluebird', 'sialia currucoides', 'invertebrate and fruit', 'grassland', 4, 'cavity', 5, 36, 'when played: play an additional bird in your grassland. pay its normal cost'))
Birds.push( new Bird("barrow's goldeneye", 'bucephala islandica', 'invertebrate and seed and fish', 'wetland', 5, 'cavity', 4, 71, 'once between turns: when another player takes the "lay eggs" action, lay 1 egg on another bird with a cavity nest'))
Birds.push( new Bird('red-winged blackbird', 'agelaius phoeniceus', 'seed', 'wetland and grassland', 2, 'bowl', 3, 33, 'when activated: tuck 1 bird from your hand behind this bird. if you do, you may also lay 1 egg on this bird'))
Birds.push( new Bird('blue-winged warbler', 'vermivora cyanoptera', 'invertebrate and invertebrate', 'grassland and forest', 8, 'bowl', 2, 20, 'none'))
Birds.push( new Bird('eastern screech-owl', 'megascops asia', 'invertebrate or rodent', 'forest', 4, 'cavity', 2, 51, 'when activated: roll all dice not in birdfeeder. if any are rodent, cache 1 rodent from the supply on this bird'))
Birds.push( new Bird('cedar waxwing', 'bombycilla cedrorum', 'fruit and fruit', 'grassland and forest', 3, 'bowl', 3, 25, 'when activated: tuck 1 from your hand behind this bird. if you do, gain 1 fruit from the supply'))
Birds.push( new Bird('spotted sandpiper', 'actitis macularius', 'invertebrate', 'wetland', 5, 'ground', 2, 38, 'when activated: all players draw 1 bird from the deck'))
Birds.push( new Bird('american oystercatcher', 'haematopus palliatus', 'invertebrate and invertebrate', 'wetland', 5, 'ground', 2, 81, 'when played: draw birds equal to the number of players +1. starting with you and proceeding clockwise, each player selects 1 of those cards and places it in their hand. you keep the extra card'))
Birds.push( new Bird("forster's tern", 'sterna forsteri', 'invertebrate or fish', 'wetland', 4, 'star', 2, 79, 'when activated: draw 1 bird. if you do, discard 1 bird from your hand at the end of your turn'))
Birds.push( new Bird("brewer's blackbird", 'euphagus cyanocephalus', 'seed and wild', 'grassland', 3, 'bowl', 3, 41, 'when activated: tuck 1 bird from your hand behind this bird. if you do, you may also lay 1 egg on this bird'))
Birds.push( new Bird('yellow-rumped warbler', 'setophaga caronata', 'invertebrate or seed or fruit', 'forest', 1, 'bowl', 4, 23, 'when activated: tuck 1 bird from your hand behind this bird. if you do, draw 1 bird'))
Birds.push( new Bird('song sparrow', 'melospiza melodia', 'invertebrate or seed or fruit', 'wetland and grassland and forest', 0, 'bowl', 5, 20, 'when activated: if this bird is to the right of all the other birds it its habitat, move it to another habitat'))
Birds.push( new Bird('cerulean warbler', 'setophaga cerulea', 'invertebrate and seed', 'forest', 4, 'bowl', 2, 20, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('wild turkey', 'meleagris gallopava', 'seed and seed and fruit', 'grassland and forest', 8, 'ground', 5, 135, 'none'))
Birds.push( new Bird('american coot', 'fulica americana', 'seed and wild', 'wetland', 3, 'platform', 5, 61, 'when activated: tuck 1 bird from your hand behind this bird, if you do, draw 1 bird'))
Birds.push( new Bird("scissor-tailed flycatcher", 'tyrannus farficatus', 'invertebrate and invertebrate and fruit', 'grassland', 8, 'bowl', 2, 38, 'when activated: all players gain 1 invertebrate from the supply'))
Birds.push( new Bird('wood stork', 'mycteria americana', 'fish and rodent and wild', 'wetland', 6, 'platform', 2, 155, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('eastern phoebe', 'sayornis phoebe', 'invertebrate or fruit', 'wetland and grassland and forest', 3, 'star', 4, 28, 'when activated: all players gain 1 invertebrate from the supply'))
Birds.push( new Bird('red-headed woodpecker', 'melanerpes erythrocephalus', 'invertebrate or seed or wild', 'wetland and grassland and forest', 4, 'cavity', 3, 43, 'when activated: gain 1 seed from the birdfeeder, if available. you may cache it on this bird'))
Birds.push( new Bird('western meadowlark', 'sturnella neglecta', 'invertebrate and seed', 'grassland', 2, 'ground', 4, 38, 'when activated: all players lay 1 egg on any 1 ground bird. you may lay 1 egg on 1 additional ground bird'))
Birds.push( new Bird('common loon', 'gavia immer', 'fish and wild', 'wetland', 6, 'ground', 1, 117, 'when activated: player(s) with the fewest birds in their wetland draw 1 bird'))
Birds.push( new Bird('northern harrier', 'circus hudsonius', 'rodent', 'wetland and grassland', 3, 'platform', 2, 109, 'when activated: look at a bird from the deck. if less than 75cm, tuck it behind this bird. if not, discard it'))
Birds.push( new Bird('common nighthawk', 'chardeiles minor', 'invertebrate and invertebrate', 'wetland and grassland and forest', 3, 'ground', 2, 56, 'when activated: if this bird is to the right of all other birds in its habitat, move it to another habitat'))
Birds.push( new Bird('hermit thrush', 'catharus guttatus', 'invertebrate and fruit and fruit', 'forest', 7, 'star', 2, 30, 'when activated: player(s) with fewest birds in their forest gain 1 food from birdfeeder'))
Birds.push( new Bird("anna's hummingbird", 'calypte anna', 'wild', 'wetland and grassland and forest', 4, 'bowl', 2, 13, 'when activated: each player gains 1 food from the birdfeeder, starting with the player of your choice'))
Birds.push( new Bird('purple martin', 'progne subis', 'invertebrate', 'wetland and grassland', 2, 'cavity', 3, 46, 'when activated: tuck 1 bird from your hand behind this bird. if you do, draw 1 bird'))
Birds.push( new Bird("sprague's pipit", 'anthus spragueii', 'invertebrate and seed', 'grassland', 3, 'ground', 3, 25, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('painted bunting', 'passerina ciris', 'invertebrate and seed and seed', 'grassland', 5, 'bowl', 4, 23, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('turkey vulture', 'cathartes aura', 'none', 'wetland and grassland and forest', 1, 'cavity', 1, 170, 'once between turns: when another players predator succeeds, gain 1 food from the birdfeeder'))
Birds.push( new Bird('sandhill crane', 'antigone canadensis', 'seed and seed and wild', 'wetland and grassland', 5, 'ground', 1, 196, 'when activated: discard 1 seed to tuck 2 birds from the deck behind this bird'))
Birds.push( new Bird('barn swallow', 'hirundo rustica', 'invertebrate', 'wetland and grassland', 1, 'star', 3, 38, 'when activated: tuck 1 bird from your hand behind this bird. if you do, draw 1 bird'))
Birds.push( new Bird("baird's sparrow", 'ammodramus bairdii', 'invertebrate and seed', 'grassland', 3, 'ground', 2, 23, 'when activated: lay 1 egg on any bird'))
Birds.push( new Bird('pine siskin', 'spinus pinus', 'seed and seed', 'forest', 3, 'bowl', 2, 23, 'when activated: tuck 1 bird from your hand behind this bird. if you do, gain 1 seed from the supply'))
Birds.push( new Bird('lazuli bunting', 'passerina amoena', 'invertebrate and seed and fruit', 'grassland', 4, 'bowl', 4, 23, 'when activated: all players lay 1 egg on any 1 bowl bird. you may lay 1 egg on 1 additional bowl bird'))
Birds.push( new Bird("cassin's finch", 'haemorhous cassinii', 'seed and fruit', 'forest', 4, 'bowl', 3, 30, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('belted kingfisher', 'megaceryle alcyon', 'fish and wild', 'wetland', 4, 'star', 4, 53, 'once between turns: when another player plays a bird in their wetland, gain 1 fish from the supply'))
Birds.push( new Bird('california quail', 'callipepla californica', 'invertebrate and seed and seed', 'grassland and forest', 3, 'ground', 6, 36, 'when activated: lay 1 egg on this bird'))
Birds.push( new Bird('canvasback', 'aythya valisineria', 'seed and wild', 'wetland', 4, 'star', 4, 82, 'when activated: all players draw 1 bird from the deck'))
Birds.push( new Bird('prothonotary warbler', 'protonotaria citrea', 'invertebrate and invertebrate and seed', 'wetland and forest', 8, 'cavity', 4, 23, 'none'))
Birds.push( new Bird('ruddy duck', 'oxyura jamaicensis', 'invertebrate or seed', 'wetland', 0, 'platform', 5, 48, 'when activated: draw 2 birds. if you do, discard 1 bird from your hand at the end of your turn')) 
Birds.push( new Bird('common raven', 'carvus corax', 'rodent and wild and wild', 'wetland and grassland and forest', 5, 'platform', 2, 135, 'when activated: discard 1 egg from any of your other birds to gain 2 wild from the supply'))
Birds.push( new Bird('great crested flycatcher', 'myiarchus crinitus', 'invertebrate and fruit', 'forest', 5, 'cavity', 3, 33, 'when activated: gain 1 invertebrate from the birdfeeder, if available'))
Birds.push( new Bird('house wren', 'troglodytes aedon', 'invertebrate', 'grassland and forest', 1, 'cavity', 5, 15, 'when played: play an additional bird in this birds habitat. pay its normal cost'))
Birds.push( new Bird("bell's vireo", 'vireo bellii', 'invertebrate and invertebrate', 'grassland and forest', 4, 'star', 2, 18, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('red-tailed hawk', 'buteo jamaicensis', 'rodent and rodent', 'wetland and grassland and forest', 5, 'platform', 2, 124, 'when activated: look at a bird from the deck. if less than 75cm, tuck it behind this bird. if not, discard it'))
Birds.push( new Bird('northern cardinal', 'cardinalis cardinalis', 'seed and fruit', 'forest', 3, 'bowl', 5, 30, 'when activated: gain 1 fruit from the supply'))
Birds.push( new Bird('ash-throated flycatcher', 'myiarchus cinerascens', 'invertebrate and invertebrate and fruit', 'grassland', 4, 'cavity', 4, 30, 'when played: lay 1 egg on each of your birds with a cavity nest'))
Birds.push( new Bird('king rail', 'rallus elegans', 'invertebrate and fish and wild', 'wetland', 4, 'platform', 6, 51, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('barred owl', 'strix varia', 'rodent', 'forest', 3, 'cavity', 2, 107, 'when activated: look at a bird from the deck. if less than 75cm, tuck it behind this bird. if not, discard it'))
Birds.push( new Bird('eastern kingbird', 'tyrannus tyrannus', 'invertebrate or fruit', 'wetland and grassland and forest', 2, 'bowl', 2, 38, 'once between turns: when another player plays a bird in their forest, gain 1 invertebrate from the supply'))
Birds.push( new Bird('american woodcock', 'scolopax minor', 'invertebrate and invertebrate and seed', 'grassland and forest', 9, 'ground', 2, 46, 'none'))
Birds.push( new Bird('hooded warbler', 'setophaga citrina', 'invertebrate and invertebrate', 'forest', 7, 'bowl', 3, 18, 'none'))
Birds.push( new Bird('white-crowned sparrow', 'lonotrichia leucophrys', 'invertebrate and seed', 'wetland and grassland and forest', 2, 'ground', 5, 25, 'when activated: if this bird is to the right of all other birds in its habitat, move it to another habitat'))
Birds.push( new Bird('purple gallinule', 'porphyrio martinicus', 'seed and fruit and wild', 'wetland', 7, 'platform', 4, 56, 'when activated: all players draw 1 bird from the deck'))
Birds.push( new Bird('white-throated swift', 'aeronautes saxatalis', 'invertebrate', 'grassland', 2, 'cavity', 2, 38, 'when activated: tuck 1 bird from your hand behind this bird. if you do, lay 1 egg on any bird'))
Birds.push( new Bird('grasshopper sparrow', 'ammodramus savannarum', 'invertebrate or seed', 'grassland', 2, 'ground', 2, 20, 'when activated: lay 1 egg on any bird'))
Birds.push( new Bird("wilson's snipe", 'gallinago delicata', 'invertebrate', 'wetland', 5, 'ground', 2, 41, 'when activated: all players draw 1 bird from the deck'))
Birds.push( new Bird('painted whitestart', 'myioborus pictus', 'invertebrate', 'forest', 1, 'ground', 3, 22, 'when activated: gain 1 invertebrate from the supply'))
Birds.push( new Bird('bald eagle', 'haliaeetus leucocephalus', 'fish and fish and rodent', 'wetland', 9, 'platform', 1, 203, 'when played: gain all fish that are in the birdfeeder'))
Birds.push( new Bird('red-breasted merganser', 'mergus serrator', 'invertebrate and fish', 'wetland', 3, 'ground', 4, 78, 'when activated: draw 2 birds, if you do, discard 1 bird from your hand at the end of your turn'))
Birds.push( new Bird('double-crested cormorant', 'phalacrocorax auritus', 'fish and wild', 'wetland', 3, 'platform', 3, 132, 'when activated: discard a fish to tuck 2 birds from the deck behind this bird'))
Birds.push( new Bird('yellow-breasted chat', 'icteria virens', 'invertebrate and fruit and fruit', 'wetland and grassland and forest', 5, 'bowl', 3, 25, 'when activated: if this bird is to the right of all other birds in its habitat, move it to another habitat'))
Birds.push( new Bird('red-shouldered hawk', 'buteo lineatus', 'rodent', 'forest', 3, 'platform', 2, 102, 'when activated: look at a bird from the deck. if less than 75cm, tuck it behind this bird. if not, discard it'))
Birds.push( new Bird('canada goose', 'branta canadensis', 'seed and seed', 'wetland and grassland', 3, 'ground', 3, 132, 'when activated: discard 1 seed to tuck 2 birds from the deck behind this bird'))
Birds.push( new Bird('blue jay', 'cyanocitta cristata', 'seed and wild', 'forest', 3, 'bowl', 2, 41, 'when activated: gain 1 seed from the birdfeeder, if available. You may cache it on this bird'))
Birds.push( new Bird('killdeer', 'charadrius vociferus', 'invertebrate or seed', 'wetland and grassland', 1, 'ground', 3, 46, 'when activated: discard 1 egg to draw 2 birds'))
Birds.push( new Bird('mallard', 'anas platyrhynchos', 'invertebrate or seed', 'wetland', 0, 'ground', 4, 89, 'when activated: draw 1 bird'))
Birds.push( new Bird('house finch', 'haemorhous mexicanus', 'seed and fruit', 'wetland and grassland and forest', 3, 'bowl', 6, 25, 'when activated: tuck 1 bird from your hand behind this bird. if you do, draw 1 bird'))
Birds.push( new Bird('northern flicker', 'colaptes auratus', 'invertebrate or seed or fruit', 'grassland and forest', 2, 'cavity', 4, 51, 'when played: gain all invertebrate that are in the birdfeeder'))
Birds.push( new Bird("bewick's wren", 'thryomanes bewickii', 'invertebrate and invertebrate and seed', 'wetland and grassland and forest', 4, 'cavity', 3, 18, 'when activated: if this bird is to the right of all other birds in its habitat, move it to another habitat'))
Birds.push( new Bird('red crossbill', 'laxia curvirastra', 'seed and seed', 'forest', 6, 'bowl', 2, 28, 'when activated: all players gain 1 seed from the supply'))
Birds.push( new Bird('anhinga', 'anhinga anhinga', 'fish and fish', 'wetland', 6, 'platform', 2, 114, 'when activated: roll all dice not in birdfeeder. if any are fish, cache 1 fish from the supply on this bird'))
Birds.push( new Bird('wood duck', 'aix sponsa', 'seed and seed and fruit', 'wetland and forest', 4, 'cavity', 4, 76, 'when activated: draw 2 birds. if you do, discard 1 bird from your hand at the end of your turn'))
Birds.push( new Bird('green heron', 'butorides virescens', 'invertebrate or fish', 'wetland', 4, 'platform', 3, 66, 'when activated: trade 1 wild for any other type from the supply'))
Birds.push( new Bird('horned lark', 'eremophila alpestris', 'invertebrate and seed', 'grassland', 5, 'ground', 4, 30, 'once between turns: when another player plays a bird in their grassland, tuck 1 bird from your hand behind this bird'))
Birds.push( new Bird("franklin's gull", 'leucophaeus pipixcan', 'fish and wild', 'wetland and grassland', 3, 'star', 2, 91, 'when activated: discard 1 egg to draw 2 birds'))
Birds.push( new Bird('broad-winged hawk', 'buteo platypterus', 'rodent', 'forest', 4, 'platform', 2, 85, 'when activated: roll all dice not in birdfeeder. if any are rodent, cache 1 rodent from the supply on this bird'))
Birds.push( new Bird('indigo bunting', 'passerina cyanea', 'invertebrate and seed and fruit', 'grassland and forest', 5, 'bowl', 3, 20, 'when activated: gain 1 invertebrate or fruit from the birdfeeder, if available'))
Birds.push( new Bird('baltimore oriole', 'icterus galbula', 'invertebrate and fruit and fruit', 'forest', 9, 'star', 2, 30, 'when activated: all players gain 1 fruit from the supply'))
Birds.push( new Bird('hooded merganser', 'laphodytes cucullatus', 'invertebrate and fish', 'wetland', 5, 'cavity', 4, 61, 'when activated: repeat one predator power in this habitat'))
Birds.push( new Bird('great blue heron', 'ardea herodias', 'invertebrate and fish', 'wetland', 5, 'platform', 2, 183, 'when played: play and additional bird in your wetland. pay its normal cost'))
Birds.push( new Bird('spotted towhee', 'pipilo maculatus', 'invertebrate or seed or fruit', 'grassland and forest', 0, 'ground', 4, 28, 'when activated: gain 1 seed from the supply'))
Birds.push( new Bird('spotted owl', 'strix accidentalis', 'rodent and rodent', 'forest', 5, 'cavity', 1, 102, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('peregrine falcon', 'falco peregrinus', 'rodent and rodent', 'wetland and grassland', 5, 'platform', 2, 104, 'when activated: look at a bird from the deck. if less than 100cm, tuck it behind this bird. if not, discard it'))
Birds.push( new Bird('great egret', 'ardea alba', 'fish and fish and rodent', 'wetland', 7, 'platform', 3, 130, 'when played: play an additional bird in your wetland. pay its normal cost'))
Birds.push( new Bird('dickcissel', 'spiza americana', 'invertebrate and seed and seed', 'grassland', 4, 'ground', 3, 25, 'when activated: tuck 1 bird from your hand behind this bird. if you do, youy may also lay 1 egg on this bird'))
Birds.push( new Bird('fish crow', 'carvus assifragus', 'fish and wild', 'wetland and grassland and forest', 6, 'platform', 2, 91, 'when activated: discard 1 egg from any of your other birds to gain 1 wild from the supply'))
Birds.push( new Bird('greater prairie-chicken', 'tympanuchus cupido', 'invertebrate and seed and seed', 'grassland', 5, 'ground', 4, 71, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('black-billed magpie', 'pica hudsonia', 'wild and wild', 'grassland', 3, 'star', 3, 64, 'once between turns: when another players predator succeeds, gain 1 food from the birdfeeder'))
Birds.push( new Bird('violet-green swallow', 'tachycineta thalassina', 'invertebrate and invertebrate', 'wetland and grassland and forest', 3, 'cavity', 3, 36, 'when activated: tuck 1 bird from your hand behind this bird. if you do, draw 1 bird'))
Birds.push( new Bird('snowy egret', 'egretta thula', 'invertebrate or fish', 'wetland', 4, 'platform', 2, 104, 'when activated: roll all dice not in birdfeeder. if any are fish, cache 1 fish on this bird'))
Birds.push( new Bird('mississippi kite', 'ictinia mississippiensis', 'invertebrate or rodent', 'grassland and forest', 4, 'platform', 1, 79, 'when activated: rol all dice not in birdfeeder. if any are rodent, cache 1 rodent from the supply on this bird'))
Birds.push( new Bird("clark's grebe", 'aechmophorus clarkii', 'fish', 'wetland', 5, 'star', 2, 61, 'when activated: draw 1 bird. if you do, discard 1 bird from your hand at the end of your turn'))
Birds.push( new Bird('yellow-bellied sapsucker', 'sphyrapicus varius', 'invertebrate and fruit', 'forest', 3, 'cavity', 3, 41, 'when activated: gain 1 invertebrate from the supply'))
Birds.push( new Bird('loggerhead shrike', 'lanius ludovicianus', 'invertebrate and rodent', 'wetland and grassland', 3, 'bowl', 4, 30, 'once between turns: when another player takes the "gain food" action, if they gain any number of rodent, cache 1 rodent from the supply on this bird'))
Birds.push( new Bird('black-crowned night-heron', 'nycticorax nycticorax', 'invertebrate and fish and rodent', 'wetland', 9, 'platform', 2, 112, 'when activated: discard 1 egg from any of your other birds to gain 1 wild from the supply'))
Birds.push( new Bird('northern shoveler', 'spatula clypeata', 'invertebrate and seed and seed', 'wetland', 7, 'ground', 4, 76, 'when activated: all players draw 1 bird from the deck'))
Birds.push( new Bird('common yellowthroat', 'geothlypis trichas', 'invertebrate', 'wetland', 1, 'bowl', 4, 18, 'when activated: draw 2 birds. if you do, discard 1 bird from your hand at the end of your turn'))
Birds.push( new Bird('red-eyed vireo', 'vireo alivaceus', 'invertebrate or fruit', 'forest', 3, 'star', 2, 25, 'when played: play an additional bird in your forest. pay its normal cost'))
Birds.push( new Bird('yellow-billed cuckoo', 'caccyzus americanus', 'invertebrate and invertebrate and wild', 'forest', 5, 'platform', 2, 46, 'once between turns: when another player takes the "lay eggs" action, lay 1 egg on a bird with a bowl nest'))
Birds.push( new Bird('chimney swift', 'chaetura pelagica', 'invertebrate and invertebrate', 'wetland and grassland and forest', 3, 'star', 2, 36, 'when activated: if this bird is to the right of all other birds in its habitat, move it to another habitat'))
Birds.push( new Bird('bronzed cowbird', 'molothrus aeneus', 'invertebrate and seed', 'grassland', 5, 'none', 0, 36, 'once between turns: when another player takes the "lay eggs" action, lay 1 egg on a bird with a bowl nest'))
Birds.push( new Bird('black tern', 'chlidonias niger', 'invertebrate or fish', 'wetland', 4, 'star', 2, 61, 'when activated: draw 1 bird. if you do, discard 1 bird from your hand at the end of your turn'))
Birds.push( new Bird('pygmy nuthatch', 'sitta pygmaea', 'invertebrate and seed', 'forest', 2, 'cavity', 4, 20, 'when activated: tuck 1 bird from your hand behind this bird. if you do, gain 1 invertebrate or seed from the supply'))
Birds.push( new Bird('rose-breasted grosbeak', 'pheucticus ludovicianus', 'invertebrate and seed and fruit', 'forest', 6, 'bowl', 3, 33, 'when activated: gain 1 seed or fruit from the birdfeeder, if available'))
Birds.push( new Bird('tree swallow', 'tachycineta bicolor', 'invertebrate and fruit', 'wetland', 3, 'cavity', 4, 38, 'when activated: tuck 1 bird from your hand behind this bird. if you do, draw 1 bird'))
Birds.push( new Bird('american white pelican', 'pelecanus erythrorhynchos', 'fish and fish', 'wetland', 5, 'ground', 1, 274, 'when activated: discard a fish to tuck 2 birds from the deck behind this bird'))
Birds.push( new Bird('osprey', 'pandion haliaetus', 'fish', 'wetland', 5, 'platform', 2, 160, 'when activated: all players gain 1 fish from the supply'))
Birds.push( new Bird("cooper's hawk", 'accipiter cooperii', 'rodent', 'forest', 3, 'platform', 2, 79, 'when activated: look at a bird from the deck. if less than 75cm, tuck it behind this bird. if not, discard it'))
Birds.push( new Bird('ruby-throated hummingbird', 'archilochus colubris', 'wild', 'wetland and grassland and forest', 4, 'bowl', 2, 10, 'when activated: each player gains 1 food from the birdfeeder. starting with the player of your choice'))
Birds.push( new Bird('willet', 'tringa semipalmata', 'invertebrate or fish', 'wetland', 4, 'ground', 2, 66, 'when activated: roll all dice not in birdfeeder. if any are fish, cache 1 fish from the supply on this bird'))
Birds.push( new Bird('inca dove', 'columbina inca', 'seed and seed', 'grassland', 2, 'platform', 4, 28, 'when played: lay 1 egg on each of your birds with a platform nest'))
Birds.push( new Bird('golden eagle', 'aquila chrysaetos', 'rodent and rodent and rodent', 'wetland and grassland', 8, 'platform', 1, 201, 'when activated: look at a bird from the deck. if less than 100cm, tuck it behind this bird. if not, discard it'))
Birds.push( new Bird("swainson's hawk", 'buteo swainsoni', 'invertebrate and rodent', 'grassland', 5, 'platform', 2, 130, 'when activated: look at a bird from the deck. if less than 75cm, tuck it behind this bird. if not, discard it'))
Birds.push( new Bird('red-breasted nuthatch', 'sitta canadensis', 'invertebrate or seed', 'forest', 2, 'cavity', 3, 23, 'when activated: cache 1 seed from the supply on this bird'))
Birds.push( new Bird('chihuahuan raven', 'carvus cryptoleucus', 'rodent and wild and wild', 'grassland', 4, 'platform', 3, 112, 'when activated: discard 1 egg from any of your other birds to gain 2 wild from the supply'))
Birds.push( new Bird('american crow', 'carvus brachyrhynchos', 'wild', 'wetland and grassland and forest', 4, 'platform', 2, 99, 'when activated: discard 1 egg from any of your other birds to gain 1 wild from the supply'))
Birds.push( new Bird('bobolink', 'dolichonyx oryzivorus', 'invertebrate and seed and seed', 'grassland', 4, 'ground', 3, 30, 'when played: lay 1 egg on each of your birds with a ground nest'))
Birds.push( new Bird('american robin', 'turdus migratorius', 'invertebrate or fruit', 'grassland and forest', 1, 'bowl', 4, 43, 'when activated: tuck 1 bird from your hand behind this bird. if you do, draw 1 bird'))
Birds.push( new Bird('white-breasted nuthatch', 'sitta carolinensis', 'invertebrate or seed', 'forest', 2, 'cavity', 3, 28, 'when activated: cache 1 seed from the supply on this bird'))
Birds.push( new Bird('bushtit', 'psaltriparus minimus', 'invertebrate and seed', 'wetland and grassland and forest', 2, 'star', 5, 15, 'when activated: tuck 1 bird from your hand behind this bird. if you do, you may also lay 1 egg on this bird'))
Birds.push( new Bird('acorn woodpecker', 'melanerpes farmicivorus', 'seed and seed and seed', 'forest', 5, 'cavity', 4, 46, 'when activated: gain 1 seed form the birdfeeder, if available. you may cache it on this bird.'))
Birds.push( new Bird('common grackle', 'quiscalus quiscula', 'seed and wild', 'wetland and grassland and forest', 3, 'bowl', 3, 43, 'when activated: tuck 1 bird from your hand behind this bird. if yo do, you may also lay 1 egg on this bird'))
Birds.push( new Bird('common merganser', 'mergus merganser', 'fish and wild', 'wetland', 5, 'cavity', 4, 86, 'when activated: roll all dice not in birdfeeder: if any are fish, cache 1 fish from the supply on this bird'))
Birds.push( new Bird('northern mockingbird', 'mimus polyglottos', 'invertebrate and fruit', 'wetland and grassland and forest', 2, 'bowl', 4, 36, 'when activated: repeat a brown power on another bird in this habitat'))
Birds.push( new Bird('american redstart', 'setophaga ruticilla', 'invertebrate and fruit', 'forest', 4, 'bowl', 2, 20, 'when activated: gain 1 food from the birdfeeder'))
Birds.push( new Bird('black vulture', 'coragyps atratus', 'none', 'forest', 2, 'cavity', 1, 150, 'once between turns: when another players predator succeeds, gain 1 food from the birdfeeder'))
Birds.push( new Bird('scaled quail', 'callipepla squamata', 'seed', 'grassland', 0, 'ground', 6, 36, 'when activated: lay 1 egg on this bird'))
Birds.push( new Bird('chestnut-collared longspur', 'calcarius arnatus', 'invertebrate and seed and seed', 'grassland', 5, 'ground', 4, 25, 'when played: draw 2 bonus cards and keep 1'))
Birds.push( new Bird('yellow-headed blackbird', 'xanthocephalus xanthocephalus', 'invertebrate and seed', 'wetland', 4, 'bowl', 3, 38, 'when activated: tuck 1 bird from your hand behind this bird. if you do, you may also lay 1 egg on this bird'))
Birds.push( new Bird('mourning dove', 'lenaida macroura', 'seed', 'wetland and grassland and forest', 0, 'platform', 5, 46, 'when activated: lay 1 egg on this bird'))
Birds.push( new Bird('juniper titmouse', 'baeolophus ridgwayi', 'invertebrate and seed', 'forest', 4, 'cavity', 3, 23, 'when activated: cache 1 seed from the supply on this bird'))
Birds.push( new Bird('brown-headed cowbird', 'molothrus ater', 'seed', 'grassland', 3, 'none', 0, 30, 'once between turns: when another player takes the "lay eggs" action, lay 1 egg on bird with a bowl nest'))
Birds.push( new Bird('red-bellied woodpecker', 'melanerpes carolinus', 'invertebrate or seed', 'forest', 1, 'cavity', 3, 41, 'when activated: gain 1 seed from the birdfeeder, if available. you may cache it on this bird'))
Birds.push( new Bird('carolina wren', 'thryothorus ludovicianus', 'invertebrate or fruit', 'forest', 1, 'cavity', 5, 20, 'when played: draw 2 birds'))
Birds.push( new Bird('eastern bluebird', 'sialia sialis', 'invertebrate and fruit', 'grassland', 4, 'cavity', 5, 33, 'when played: play an additional bird in your grassland. pay its normal cost'))
Birds.push( new Bird('pied-billed grebe', 'podilymbus podiceps', 'invertebrate or fish', 'wetland', 0, 'platform', 4, 41, 'when activated: draw 2 birds. if you do, discard 1 bird from your hand at the end of your turn'))
Birds.push( new Bird("vaux's swift", 'chaetura vauxi', 'invertebrate', 'forest', 2, 'cavity', 3, 31, 'when activated: tuck 1 bird from your hand behind this bird. if you do, gain 1 invertebrate from the supply'))
Birds.push( new Bird('ferruginous hawk', 'buteo regalis', 'rodent and rodent', 'grassland', 6, 'platform', 2, 142, 'when activated: roll all dice not in birdfeeder. if any are rodent, cache 1 rodent from the supply on this bird'))
Birds.push( new Bird('dark-eyed junco', 'junco hyemalis', 'invertebrate and seed', 'grassland and forest', 3, 'ground', 3, 23, 'when activated: tuck 1 bird from your hand behind this bird. if you do, gain 1 seed from the supply'))
Birds.push( new Bird('great horned owl', 'bubo virginianus', 'rodent and rodent and rodent', 'forest', 8, 'platform', 2, 112, 'when activated: look at a bird from the deck. if less than 100cm, tuck it behind this bird. if not, discard it'))
Birds.push( new Bird("steller's jay", 'cyanocitta stelleri', 'seed and seed and wild', 'forest', 5, 'bowl', 2, 48, 'when activated: gain 1 seed from the birdfeeder, if available. you may cache it on this bird'))
Birds.push( new Bird('mountain chickadee', 'poecile gambeli', 'invertebrate or seed', 'forest', 2, 'cavity', 3, 23, 'when activated: cache 1 seed from the supply on this bird'))
Birds.push( new Bird('carolina chickadee', 'poecile carolinensis', 'invertebrate or seed', 'forest', 2, 'cavity', 3, 20, 'when activated: cache 1 seed from the supply on this bird'))
Birds.push( new Bird("cassin's sparrow", 'peucaea cassinii', 'invertebrate and seed', 'grassland', 3, 'ground', 2, 20, 'when activated: lay 1 egg on any bird'))
Birds.push( new Bird('downy woodpecker', 'picoides pubescens', 'invertebrate or seed or fruit', 'forest', 3, 'cavity', 2, 30, 'when played: play an additional bird in your forest, pay its normal cost'))


Bonuscards.push( new BonusCard('Wildlife Gardener', 'Birds with bown nests', '4-5 birds: 4 points, 6+ birds: 7 points', '31%'))
Bonuscards.push( new BonusCard('Omnivore Expert', 'Birds that eat wild', '2 points per bird', '16%'))
Bonuscards.push( new BonusCard('Wetland Scientist', 'Birds that can only live in wetlands', '3-4 birds: 3, 5 birds: 7 points', '26%'))
Bonuscards.push( new BonusCard('Anatomist', 'Birds with body parts in their names', '2-3 birds: 3 points, 4+ birds: 7 points', '22%'))
Bonuscards.push( new BonusCard('Backyard Birder', 'Birds worth less than 4 points', '5-6 birds: 3 points, 7+ birds: 6 points', '42%'))
Bonuscards.push( new BonusCard('Bird Counter', 'Birds with a flock power', '2 points per bird', '15%'))
Bonuscards.push( new BonusCard('Bird Feeder', 'Birds that eat seeds', '5-7 birds: 3 points, 8+ birds: 7 points', '44%'))
Bonuscards.push( new BonusCard('Breading Manager', 'Birds that have at least 4 eggs laid on them', '1 point per bird', '28%'))
Bonuscards.push( new BonusCard('Cartographer', 'Birds with geography terms in their name', '2-3 birds: 3 points, 4+ birds: 7 points', '21%'))
Bonuscards.push( new BonusCard('Ecologist', 'Birds in your habitat with the fewest birds', '2 points per bird', 'none'))
Bonuscards.push( new BonusCard('Enclosure Builder', 'Birds with ground nests', '4-5 birds: 4 points, 6+ birds: 7 points', '31%'))
Bonuscards.push( new BonusCard('Falconer', 'Birds with a predator power', '2 points per bird', '13%'))
Bonuscards.push( new BonusCard('Fishery Manager', 'Birds that eat fish', '2-3 birds: 3 points, 4+ birds: 8 points', '18%'))
Bonuscards.push( new BonusCard('Food Web Expert', 'Birds that eat only invertebrate', '2 points per bird', '9%'))
Bonuscards.push( new BonusCard('Forester', 'Birds that can only live in forest', '3-4 birds: 4 points, 5 birds: 8 points', '24%'))
Bonuscards.push( new BonusCard('Historian', 'Birds named after a person', '2 points per bird'))
Bonuscards.push( new BonusCard('Large Bird Specialist', 'Birds with wingspans over 65cm', '4-5 birds: 3 points, 6+ birds: 6 points', '35%'))
Bonuscards.push( new BonusCard('Nest Box Builder', 'Birds with cavity nests', '4-5 birds: 4 points, 6+ birds: 7 points', '31%'))
Bonuscards.push( new BonusCard('Oologist', 'Birds that have at least 1 egg laid on them', '7-8 birds: 3 points, 9+ birds: 6 points', 'none'))
Bonuscards.push( new BonusCard('Platform Builder', 'Birds with platform nests', '4-5 birds: 4 points, 6+ birds: 7 points', '31%'))
Bonuscards.push( new BonusCard('Viticulturalist', 'Birds that eat fruit', '2-3 birds: 3 points, 4+ birds: 7 points', '22%'))
Bonuscards.push( new BonusCard('Rodentologist', 'Birds that eat rodents', '2 points per bird', '15%'))
Bonuscards.push( new BonusCard('Visionary Leader', 'Bird cards in hand at end of game', '5-7 birds: 4 points, 8+ birds: 7 points', 'none'))
Bonuscards.push( new BonusCard('Prairie Manager', 'Birds that can only live in grassland', '2-3 birds: 3 points, 4+ birds: 8 points', '19%'))
Bonuscards.push( new BonusCard('Photographer', 'Birds with colours in their names', '4-5 birds: 3 points, 6+ birds: 6 points', '34%'))
Bonuscards.push( new BonusCard('Passerine Specialist', 'Birds with wingspans 30cm or less', '4-5 birds: 3 points, 6+ birds: 6 points', '35%'))
module.exports = {Birds, Bonuscards}